### ISSUE TITLE
Informational links for Pools on website links cannot be opened

### ISSUE THREAD

**Issue by bambalados** [IPOR-Labs/ipor-protocol#679]
![CleanShot 2023-10-31 at 11 12 22@2x](https://github.com/IPOR-Labs/ipor-protocol/assets/49643174/e907d856-4db1-4e0d-a979-dd9fae7bfa33)

Informational Link when depositing LP manually cannot be openend. 

https://app.ipor.io/deposit/usdc -> then click on manual, and you 'll find the links

**Comment by maciek-ipor** [comment]
Hi @bambalados, thank you for your report. Could you please provide information what browser do you use and could you check if on any other browser the issue still occurs?

**Comment by bambalados** [comment]
Yes, problem resolved. Links seem to be updated. Was using Brave and Safari.
